name: Deploy

on:
  push:
    branches: [ main ]  

# top-level call-out of the different tasks within the workflow
jobs:
  build:
    name: Build and Deploy
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Deploy to render 
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}